files:
  - source: /udata_front/translations/udata-front.pot
    translation: /udata_front/translations/%two_letters_code%/LC_MESSAGES/%file_name%.po
  - source: /udata_front/theme/gouvfr/translations/gouvfr.pot
    translation: >-
      /udata_front/theme/gouvfr/translations/%two_letters_code%/LC_MESSAGES/%file_name%.po
