version: "3"
services:
    db:
        image: mongo:3.6
        volumes:
          - ../../udata/data/db:/data/db
        expose:
          - "27017"
        ports:
        - "27017:27017"

    broker:
        image: redis
        volumes:
          - ../../udata/data/broker:/data
        expose:
          - "6379"
        ports:
          - "6379:6379"

    search:
        image: udata/elasticsearch:2.4.5
        volumes:
          - ../../udata/data/search/data:/usr/share/elasticsearch/data
        expose:
          - "9200"
        ports:
          - "9200:9200"
